// Original roll-table content for the "Instant Inspiration" bonus pages.
// System-neutral on purpose: no names or creatures owned by any RPG publisher.

export const NPC_QUIRKS = [
  'Speaks only in questions when nervous',
  'Hums the same four notes, over and over',
  'Counts their coins twice, then once more',
  'Refers to themself in the third person',
  'Sharpens a knife that is already sharp',
  'Laughs a beat too late at every joke',
  'Wears a ring on every finger, each with a story',
  'Sniffs every dish suspiciously before eating',
  "Gets the party's names wrong, differently each time",
  'Keeps a pet beetle in a matchbox',
  "Finishes other people's sentences, usually wrong",
  'Quotes proverbs nobody has ever heard',
  'Never sits with their back to a door',
  'Writes everything down in a tiny notebook',
  'Whistles through a gap in their front teeth',
  'Knocks on wood whenever luck is mentioned',
  'Shakes hands with both hands, too long',
  'Is warmer to animals than to people',
  'Has a dramatic sigh for every occasion',
  'Always smells faintly of woodsmoke and cloves',
  'Claims to be distantly related to royalty',
  'Fidgets with a lucky copper coin',
  'Answers questions with long, winding stories',
  'Squints as if every room is too bright',
  'Collects buttons from strangers',
  'Sings instead of speaking when drunk',
  'Avoids stepping on cracks between cobbles',
  'Has an unexplained fear of ducks',
  'Calls everyone "friend," even enemies',
  'Keeps adjusting a hat that fits fine',
  'Whispers, even when shouting would help',
  'Always chewing on a grass stalk or quill',
  'Keeps a running tally of favors owed',
  'Unfailingly polite, which is somehow threatening',
  'Remembers every face but never a name',
  'Blesses each sneeze in a different god’s name',
  'Carries a heavy book they never open',
  'Eats constantly, and insists you share',
  'Talks about the weather as if it holds grudges',
  "Can't resist correcting anyone's grammar",
  'Taps out rhythms like a secret code',
  'Gives everyone a nickname within a minute',
  'Overly proud of a small, ugly scar',
  'Cracks knuckles before anything important',
  'Stares just past you when talking',
  'Brags about a monster they "almost" killed',
  'Always has a better story than yours',
  'Carries a flower that never wilts',
  'Laughs at their own jokes before the punchline',
  'Only trusts people who own a dog',
  'Keeps glancing over their shoulder',
  "Talks to their late spouse's locket",
  'Uses big words, mostly incorrectly',
  'Haggles over everything, even gifts',
  'Has a pet crow that repeats their secrets',
  'Scratches their nose whenever they lie',
  'Straightens anything that hangs crooked',
  'Reads fortunes from a deck missing three cards',
  'Speaks in a stiff, old-fashioned formal tone',
  'Sweats heavily whenever magic is used nearby',
  "Offers unwanted advice on everyone's posture",
  'Is certain the party are spies',
  'Keeps trying to recruit the party to a guild',
  "Walks with a cane they clearly don't need",
  'Snorts when laughing, then apologizes',
  'Wears mismatched boots on purpose',
  "Knows everyone's business and shares it freely",
  'Pauses mid-sentence to listen to something',
  'Writes terrible poetry and reads it aloud',
  'Salutes, bows and curtsies all at once',
  'Loves gossip but swears they hate it',
  'Owes money to someone the party knows',
  'Endlessly polishes a battered old helmet',
  'Refuses to say the name of a certain town',
  'Mentions their mother in every conversation',
  'Believes they are cursed. They may be right',
  'Carries tiny wooden toys for children',
  'Says "as they say" before made-up sayings',
  "Can't stand silence and fills it immediately",
  'Claims a deadly allergy to cats',
  'Sketches everyone they meet',
  'Speaks slowly, weighing every single word',
  'Is always mid-meal when anyone visits',
  'Wears armor everywhere, even to weddings',
  'Hides behind a thick accent that keeps slipping',
  'Keeps a ledger of every insult received',
  "Won't help until you answer a riddle",
  'Is deathly afraid of deep water',
  'Tries to sell the party something every time',
  'Has a laugh that fills the whole room',
  'Checks a pocket watch that stopped years ago',
  'Treats their old mule like royalty',
  'Always cold, wrapped in too many cloaks',
  'Winks after every statement, true or not',
  'Believes all dreams are prophecies',
  'Quietly notices what everyone else misses',
  "Keeps a lock of someone's hair in a pouch",
  'Flinches at loud noises; an old soldier',
  'Only drinks milk and defends this loudly',
  'Is secretly, and badly, in disguise',
];

export const TAVERN_NAMES = [
  'The Gilded Gizzard',
  'The Drowned Lantern',
  'The One-Eyed Badger',
  'The Crooked Crown',
  'The Wandering Kettle',
  'The Last Honest Coin',
  "The Sleeping Giant's Boot",
  'The Salt & Thistle',
  'The Rusty Portcullis',
  'The Moth & Moonlight',
  'The Burnt Biscuit',
  'The Hollow Harp',
  'The Merry Gallows',
  'The Bent Horseshoe',
  'The Copper Cauldron',
  'The Weeping Willow Inn',
  'The Three Bad Wizards',
  'The Tipsy Wyvern',
  'The Goose & Gauntlet',
  'The Quiet Hound',
];

export const RUMORS = [
  "The miller's new apprentice casts no shadow at noon.",
  "Someone is paying triple for rat tails, and won't say why.",
  'The old lighthouse lit itself last night. It has no keeper.',
  "A noble's heir vanished on the north road, with the ransom.",
  'The well water has tasted of copper since the bells stopped.',
  'A traveling circus arrived with one more wagon than it left with.',
  "The temple's holy relic is a fake. The real one was sold.",
  'Wolves by the quarry have been seen walking on two legs.',
  "The tax collector never came back from the hill villages.",
  "A map to a sunken vault is sewn into a beggar's coat.",
  'The mayor meets a hooded stranger every new moon.',
  'Graves in the churchyard were dug up, then filled back in.',
  "A dragon's egg is for sale on the black market. Supposedly.",
  'The ferryman now charges passage in secrets, not coin.',
  'Border soldiers are deserting. Something scared them off.',
  'The marsh witch grants wishes, but always takes a memory.',
  "The blacksmith's forge burns blue, and he won't say why.",
  'The village children all keep drawing the same door.',
  'The bard who sang here last week was found turned to stone.',
  "The duke's fleet sailed out full and came back empty.",
];

export const VILLAIN_MOTIVES = [
  'Revenge for a wrong done by the heroes’ allies',
  'To bring back someone they lost, at any cost',
  'Believes the world must burn to be reborn',
  'Guarding a secret that would topple a kingdom',
  'Claiming a throne they believe is theirs by right',
  'A pact must be paid, or their soul is forfeit',
  'Wants to be remembered forever, as anything',
  "Truly believes they're saving everyone",
  'Pure greed for a legendary treasure',
  'Ending a war by any means necessary',
  'Wants to become a god, or kill one',
  'Serving a master far worse than themself',
  'Proving their family wrong about them',
  'Freeing an imprisoned people, monsters included',
  'Escaping a prophecy by rewriting it',
  'Curing a plague they accidentally caused',
  'Collecting something from each of the heroes',
  'Love, twisted into obsession',
  'Boredom: immortality has made them cruel',
  'Reclaiming land stolen from their people',
];

export const PLOT_TWISTS = [
  'The quest giver is the real villain.',
  "The villain is a hero's missing relative.",
  'The treasure is a living being.',
  'The monster was protecting the town, not threatening it.',
  'The heroes were hired to steal their own reward.',
  'Two rival factions are secretly led by the same person.',
  'A "dead" ally faked their death to spy on the party.',
  "The map is accurate. It's just 300 years old.",
  'The prophecy is about the villain, not the heroes.',
  'The villain wants the heroes to succeed, for now.',
  "The kingdom's savior made a terrible bargain.",
  'The dungeon is inside something alive.',
];

export const TREASURES = [
  'A compass that points to the last thing you lost',
  'A teacup that refills with whatever you last drank',
  'A key that opens any lock, but only once',
  'A mirror that shows the room as it was yesterday',
  'A bottled storm, rattling against the glass',
  "A coin with a stranger's face on both sides",
  'A map that redraws itself as you walk',
  'A silver bell no one else can hear',
  'A quill that can only write the truth',
  'A fox-shaped cloak pin that sometimes yawns',
  'A jar of fireflies that never die',
  'A one-string lute that can play any song',
  'A candle that burns cold and casts no light',
  "A pressed flower from a land that doesn't exist",
  'A ring that tightens when someone lies to you',
  'A seed that grows into a door',
  'A glass eye that sees clearly through fog',
  'Two dice that always add up to seven',
  'A letter to one of the heroes, dated 50 years ago',
  'A crown of antlers, always warm to the touch',
];

export const OPENERS = [
  'Start mid-chase. Something is gaining on them, fast.',
  'A bleeding stranger bursts in and hands them a package.',
  "They wake up somewhere they didn't fall asleep.",
  'The bridge ahead collapses just as they reach it.',
  'A messenger arrives with the worst possible news.',
  'An old enemy offers a truce, and a warning.',
  'Funeral bells ring for someone they know.',
  'A rival party beats them to their destination.',
  'A storm drives them into a shelter that is already occupied.',
  'Their reward is stolen while they sleep.',
  "A child begs them to find a lost pet. It isn't a normal pet.",
  "Everyone in town has forgotten the heroes' names.",
];

export const HOUSE_SPECIALS = [
  'Smoked eel pie, baked "for luck"',
  'Black ale brewed with burnt honey',
  'Mushroom stew. Nobody will name the mushrooms',
  'Fire cider that makes your ears ring',
  'Roast goose stuffed with apples and chestnuts',
  "Grandmother's broth, served cold, oddly delicious",
  'Spiced wine that changes color as it cools',
  'Pickled eggs from a jar older than the tavern',
  'Blackberry mead, sweet enough to glue your teeth',
  'Salt-crusted river fish, eaten with your fingers',
  "Hard cheese with a rind you shouldn't eat",
  "Mystery skewers. Tuesday's are best. Don't ask.",
];

export const CALLING_CARDS = [
  'A single black feather left at every scene',
  'Every candle in the room goes out at once',
  'Witnesses hum the same nursery rhyme',
  'Chalk circles appear on doors overnight',
  'Flowers wilt in a perfect ring',
  'Letters sealed with a thumbprint in red wax',
  'Animals flee the area a day before',
  'A playing card, always the same one',
  'Mirrors crack in the shape of a crown',
  'Church bells ring backwards at midnight',
];

export const OMENS = [
  'Fog so thick that sound gets lost in it',
  'A red moon, and every dog howls at once',
  'Warm rain that smells of iron',
  "Midsummer hail that doesn't melt",
  'Hundreds of crows gathering in silence',
  'Wind blowing from every direction at once',
  'A rainbow at midnight',
  'Snow falls, but only on the heroes',
  'The river runs backwards for an hour',
  'Sudden, total silence: no birds, no wind',
];
